version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
#      cache_from:
#        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    command: /start
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    expose:
      - 8000
    env_file: .env

  db:
    image: postgres:12.0-alpine
    env_file:
      - .env
    volumes:
      - ./init_prod.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    ports:
      - 80:80
    depends_on:
      - web


volumes:
  postgres_data:
  staticfiles:
  mediafiles: