# Generated by Django 2.2.2 on 2019-06-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Comers', max_length=20)),
                ('slug', models.SlugField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('english_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('christian', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('hometown', models.CharField(blank=True, max_length=50, null=True)),
                ('first_time', models.DateField(null=True)),
                ('habits', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('group_leader', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(max_length=31)),
                ('group', models.ForeignKey(on_delete=True, related_name='members', to='catalog.Group')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(blank=True, max_length=20, null=True)),
                ('account_id', models.CharField(blank=True, max_length=20, null=True)),
                ('member', models.ForeignKey(on_delete=True, related_name='social_media_accounts', to='catalog.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(blank=True, max_length=20, null=True)),
                ('service_date', models.DateField(null=True)),
                ('slug', models.SlugField(max_length=63)),
                ('coordinator', models.ManyToManyField(null=True, to='catalog.Member')),
                ('servants', models.ManyToManyField(null=True, related_name='services', to='catalog.Member')),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ['service_date', 'service_category'],
            },
        ),
    ]
