# Generated by Django 2.2.2 on 2019-06-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190615_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AlterField(
            model_name='service',
            name='coordinator',
            field=models.ManyToManyField(null=True, to='user.Member'),
        ),
        migrations.AlterField(
            model_name='service',
            name='servants',
            field=models.ManyToManyField(null=True, related_name='services', to='user.Member'),
        ),
    ]
