# Generated by Django 2.2.2 on 2019-06-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190617_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service_date'], 'verbose_name': 'Service'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='service',
            name='servants',
        ),
        migrations.CreateModel(
            name='ServantTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('slug', models.SlugField(max_length=63)),
                ('coordinator', models.ManyToManyField(null=True, to='user.Member')),
                ('servants', models.ManyToManyField(null=True, related_name='servant_teams', to='user.Member')),
                ('service', models.ForeignKey(on_delete=True, related_name='servant_teams', to='user.Service')),
            ],
        ),
    ]
