# Generated by Django 2.2.2 on 2019-06-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190617_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servantteam',
            name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='service_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
