# Generated by Django 2.2.2 on 2019-06-19 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190618_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service_date', 'service_category'], 'verbose_name': 'Service'},
        ),
    ]
