# Generated by Django 2.2.2 on 2019-06-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190618_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='coordinator',
            field=models.ManyToManyField(null=True, to='user.Member'),
        ),
        migrations.AddField(
            model_name='service',
            name='servants',
            field=models.ManyToManyField(null=True, related_name='services', to='user.Member'),
        ),
        migrations.DeleteModel(
            name='ServantTeam',
        ),
    ]
