# Generated by Django 2.2.2 on 2019-06-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190618_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
